# CD pipeline to build, package, and publish a Chrome Extension

name: Chrome Extension CD
on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Build
        run: |
          npm ci
          npm run build
          npm run zip
      - name: Upload
        uses: mnao305/chrome-extension-upload@v4.0.0
        with:
          refresh-token: ${{secrets.REFRESH_TOKEN}}
          client-id: ${{secrets.CLIENT_ID}}
          client-secret: ${{secrets.CLIENT_SECRET}}
          file-path: './build.zip'
          extension-id: ${{secrets.APP_ID}}
          publish: false
      - name: Notify for publishing confirmation
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: New Panda Upload Success
          body: CI/CD pipeline succeeded. Awaiting publishing.
          # Required recipients' addresses:
          to: jtchengdev@gmail.com
          # Required sender full name (address can be skipped):
          from: Panda CI/CD # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional attachments:
          attachments: ./build/manifest.json
